### ISSUE TITLE
Compatibility with PSE/PS2 HSMs

### ISSUE THREAD

**Issue by praffulkapil** [ThalesGroup/pycryptoki#20]
Hi ,

Does this wrapper Lib work well with PSE (Protect Server External)/PS2 HSMs simulator of Gemalto/Thales ?
Currently I can afford PSE/PS2 simulator(s/w HSM) only for initial development environment.

Regards,
Prafful

**Comment by astraw38** [comment]
Hi @praffulkapil , it should theoretically work. I assume the PSE uses libCryptoki & PKCS11 as well. If it doesn't, let me know what error message you get.

**Comment by rosennej** [comment]
Protect Server has its own set of PKCS#11 extensions, both functions and constants.
