### ISSUE TITLE
store private key inside thales hsm

### ISSUE THREAD

**Issue by lokeish** [ThalesGroup/pycryptoki#23]
I want to store a private key inside hsm and when ever i need it need to extracted from hsm(Extractable = True), so for that i tried using create_object function i tried to create a template but it throws an exception with CKA_TEMPLATE_INCONSISTENT.
What is the correct syntax for that and provide a sample to template.

Is the template for get_attribute_value and set_attribute_value will be same?

**Comment by astraw38** [comment]
To insert a private key onto a Luna HSM, you would need to use ``c_unwrap_key``. If it's a RSA or ECC key, it'll need to be DER encoded. If it's an AES/DES key, just raw bytes are fine. Create a temporary AES key on the HSM (with ``CKA_ENCRYPT=1`` and ``CKA_UNWRAP=1``), encrypt the key data (the .der or the raw bytes) with ``CKM_AES_CBC_PAD``, then call ``c_unwrap_key`` (with the same mechanism).



``c_create_object`` should only be used to create: data objects, certificate objects, or public keys. 


The following is an example function that will let you inject an encoded key:

```py

def inject_secret_key(h_session, key_data, template):
    wrapping_template = {
        CKA_CLASS: CKO_SECRET_KEY,
        CKA_KEY_TYPE: CKK_AES,
        CKA_TOKEN: False,
        CKA_PRIVATE: True,
        CKA_SENSITIVE: True,
        CKA_ENCRYPT: True,
        CKA_UNWRAP: True,
        CKA_VALUE_LEN: 32,
    }

    wrapping_iv = [
        0x00,
        0x01,
        0x02,
        0x03,
        0x04,
        0x05,
        0x06,
        0x07,
        0x10,
        0x11,
        0x12,
        0x13,
        0x14,
        0x15,
        0x16,
        0x17,
    ]

    wrapping_key = c_generate_key_ex(h_session, CKM_AES_KEY_GEN, wrapping_template)
    try:
        mechanism = Mechanism(mech_type=CKM_AES_CBC_PAD, params={"iv": wrapping_iv})
        encrypted_key = c_encrypt_ex(h_session, wrapping_key, data=key_data, mechanism=mechanism)

        injected_key_handle = c_unwrap_key_ex(
            h_session, wrapping_key, encrypted_key, template, mechanism=mechanism
        )
    finally:
        c_destroy_object(h_session, wrapping_key)

    return injected_key_handle
```


Finally, a handful of attributes that are used for creating a key are not used when unwrapping a key. For example, CKA_VALUE_LEN is not needed if you're unwrapping an AES key onto the HSM.
