### ISSUE TITLE
ctypes.ArgumentError when calling c_initialize_ex function

### ISSUE THREAD

**Issue by manuelaguadomtz** [ThalesGroup/pycryptoki#37]
Hi:

I am trying to call the c_initialize_ex function with the CKF_OS_LOCKING_OK flags but I am getting the following error

ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type 

`
from pycryptoki.defines import CKF_OS_LOCKING_OK
from pycryptoki.session_management import c_initialize_ex

c_initialize_ex(flags=CKF_OS_LOCKING_OK)
`

The code is running on Windows with LunaClient v2.2.3 installed.

I know this is an old version of LunaClient. Are there compatibility issues?

Thanks in advance!

**Comment by astraw38** [comment]
Nope - just a common programming error! 

Should be casting a pointer to the init struct to c_void_p, not the struct itself. I'll push up a fix shortly

**Comment by manuelaguadomtz** [comment]
Thank you very much for the quick answer!
