### ISSUE TITLE
Provide sample codes?

### ISSUE THREAD

**Issue by LudovicRousseau** [ThalesGroup/pycryptoki#4]
Could you provide simple sample codes to show how to use the wrapper?
Do you have the API documentation available as HTML pages somewhere?

I am the current maintainer of https://github.com/LudovicRousseau/PyKCS11

**Comment by astraw38** [comment]
We only have a very basic sample in the [docs](http://pycryptoki.readthedocs.io/en/latest/) (or you could look at the functional tests -- they do key generation, sign/verify/encrypt/decrypt/wrap etc).

API Docs are also there -- though they do need to be updated with proper links.

**Comment by LudovicRousseau** [comment]
I propose to add a link to http://pycryptoki.readthedocs.io/en/latest/index.html in the ``README.md`` file.

From the doc I do not understand how to specify a specific PKCS#11 library to use.

**Comment by astraw38** [comment]
Sorry it was not obvious -- it's the docs|latest tag in the readme. I can make that more clear.


And support for other PKCS11 libraries is not intended and isn't likely to be supported by us, sorry (though it wouldn't be difficult to add).

**Comment by bandtank** [comment]
This library was probably a lot of work to create, so not providing more examples doesn't make a lot of sense to me. We considered using about 20 Safenet HSMs, but the integration effort was too substantial and this type of library would have helped had it been more clearly documented.
