### ISSUE TITLE
Adding compatibility to other PKCS#11 libraries?

### ISSUE THREAD

**Issue by Muzosh** [ThalesGroup/pycryptoki#40]
Hello, I love your library but I would love to use it with my own PKCS#11 library. Is this functionality in the scope of this project?

If not, I would like to propose to change repository name, since "pycryptoki" suggests it should load other PKCS#11 libraries. Thanks

**Comment by astraw38** [comment]
As much as possible, we try to be P11 compliant -- and we do late binding of calls -> C lib calls. So you can use other libraries if you really wanted to, just you might run into issues based on different implementations of P11 (mostly around constants, templates, extensions, etc). 

Support for other implementations is not planned.

**Comment by hasnainvirk** [comment]
From where we can install SafeNEt Cryptoki lib ?

**Comment by LudovicRousseau** [comment]
@Muzosh You can have a look at https://github.com/LudovicRousseau/PyKCS11 for another Python wrapper above PKCS#11.
It is easy to use with **any** PKCS#11 library.
https://github.com/LudovicRousseau/PyKCS11/blob/master/samples/encrypt.py#L25
